name: CD

on:
    push:
        branches: [staging]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install Aftman
              uses: ok-nick/setup-aftman@v0.3.0

            - name: Install Aftman Tools
              run: aftman install

            - name: Install dependencies
              run: npm install

            - name: Compile TypeScript
              run: |
                  npx rbxtsc

            - name: Build Game
              run: |
                  npm run build-rbx

            - name: Deploy to Roblox
              run: |
                  rbxcloud experience publish --filename build.rbxl --place-id 126529320148429 --universe-id 7238338295 --version-type published --api-key ${{ secrets.API_KEY }}
