-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	images = {
		archer = "rbxassetid://16726140525",
		cash = "rbxassetid://16726140587",
		heart = "rbxassetid://16726140716",
		heart_glow = "rbxassetid://16726140894",
		left_mouse_button = "rbxassetid://16726140962",
		pixel_heart = "rbxassetid://16726141065",
		q_button = "rbxassetid://16726141133",
		r_button = "rbxassetid://16726141209",
		stripes = "rbxassetid://16726141326",
		x_button = "rbxassetid://16726141457",
	},
}