-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	images = {
		archer = "rbxassetid://15176776753",
		cash = "rbxassetid://15017842957",
		heart = "rbxassetid://14975106821",
		heart_glow = "rbxassetid://14975200427",
		left_mouse_button = "rbxassetid://15521307634",
		pixel_heart = "rbxassetid://15771563590",
		q_button = "rbxassetid://15521240434",
		r_button = "rbxassetid://15521240550",
		stripes = "rbxassetid://15771465269",
		x_button = "rbxassetid://16724865948",
	},
}