-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	images = {
		cash = "rbxassetid://15017842957",
		heart = "rbxassetid://14975106821",
		heart_glow = "rbxassetid://14975200427",
	},
}